[workspace]
resolver = "2"
members = [ "crates/*", "xtask" ]
exclude = [ 
    "old",
    "crates/derivatives",
    "crates/relational",
    "crates/input",
]

[workspace.dependencies]
anyhow = { version = "1.0.89", default-features = false }
arrayvec = { version = "0.7.6", default-features = false }
chrono = { version = "0.4.38", default-features = false }
chrono-tz = { version = "0.10.0", default-features = false }
itertools = { version = "0.13.0", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
rust_decimal = { version = "1.36.0", default-features = false }
serde = { version = "1.0.210", default-features = false }
serde_json = { version = "1.0.128", default-features = false }
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3.18", default-features = false }
uuid = { version = "1.10.0", default-features = false }
html5ever = { version = "0.35.0", default-features = false }
futures = { version = "0.3", default-features = false }
url = { version = "2.5.7", default-features = false }
















