[package]
name = "date"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "calc-ymd"
harness = false
path = "src/calc-ymd.rs"

[dependencies.serde]
workspace = true
optional = true

[dependencies.chrono]
workspace = true
default-features = false
optional = true 

[dependencies.calendrical_calculations]
#workspace = true
default-features = false
git = "https://github.com/esheppa/icu4x"
rev = "41c1c4ad5d03f1a26cfb7a72b945eec937eb98b9"
#optional = true 
#version = "0.2.2"


[dev-dependencies]
serde_json = "1.0.115"
chrono-tz = "0.10.0"
chrono = "0.4"
calendrical_calculations = "0.2.2"
jiff = "0.2.13"
criterion = "0.5.0"

[features]
serde = ["dep:serde","chrono/serde"]
std = ["chrono/std"]


