[package]
name = "timeseries"
version = "0.1.0"
edition = "2021"

[dependencies.serde]
workspace = true
features = ["derive"]

[dependencies.num-traits]
workspace = true


[dependencies.resolution]
path = "../resolution"
features = ["serde"]
