use super::{ARCHIVE, CURRENT, NEMWEB};
use alloc::{format, string::String};
use chrono::{DateTime, NaiveDate, Utc};

#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum CurrentFolder {
    AdjustedPricesReports,
    AltLimits,
    AncillaryServicesPayments,
    AuctionUnitsReports,
    BidmoveComplete,
    BidmoveSummary,
    Billing,
    CauserPays,
    CauserPaysElements,
    CauserPaysRslcpf,
    CauserPaysScada,
    CDEII,
    CSCCSPConstraintList,
    CSCCSPSettlements,
    DailyReports,
    DAILYOCD,
    DirectionsReconciliation,
    DispatchIRSR,
    DISPATCHNEGATIVERESIDUE,
    DispatchReports,
    DispatchSCADA,
    DispatchISReports,
    DispatchpricesPREAP,
    DWGM,
    ECGS,
    GasSupplyGuarantee,
    GBB,
    GSH,
    HighImpactOutages,
    HistDemand,
    IBEI,
    MarginalLossFactors,
    MarketNotice,
    MCCDispatch,
    MediumTermPASAReports,
    MktsuspPricing,
    MMSDataModelReport,
    MTPASADUIDAvailability,
    MTPASARegionAvailability,
    Network,
    NextDayActualGen,
    NEXTDAYAVAILSUBMISSCLUSTER,
    NEXTDAYAVAILSUBMISSDAY,
    NextDayDispatch,
    NextDayIntermittentDS,
    NEXTDAYMCCDISPATCH,
    NextDayOfferEnergy,
    NextDayOfferFCAS,
    NextDayPreDispatch,
    NextDayPreDispatchD,
    NextDayTrading,
    OperationalDemand,
    P5Reports,
    PasaSnap,
    PD7Day,
    PDPASA,
    PredispatchIRSR,
    PredispatchReports,
    PredispatchSensitivities,
    PredispatchISReports,
    PublicPrices,
    PublishedModelDataAccess,
    RegionalSummaryReport,
    ReserveContractRecovery,
    ROOFTOPPVActual,
    ROOFTOPPVForecast,
    Settlements,
    SEVENDAYOUTLOOKFULL,
    SEVENDAYOUTLOOKPEAK,
    ShortTermPASAReports,
    SRABids,
    SRANSRRECONCILIATION,
    SRAOffers,
    SRAResults,
    STTM,
    SupplyDemand,
    TradingCumulativePrice,
    TradingIRSR,
    TradingISReports,
    VicGas,
    VwaFcasPrices,
    WDRCAPACITYNOSCADA,
    WeeklyBulletin,
    WeeklyConstraintReports,
    YesterdaysBidsReports,
    YesterdaysMNSPBidsReports,
}

impl CurrentFolder {
    pub fn url(&self) -> String {
        format!("{NEMWEB}/{CURRENT}/{}", self.folder_name())
    }
    pub fn folder_name(&self) -> &'static str {
        match self {
            CurrentFolder::AdjustedPricesReports => "Adjusted_Prices_Reports",
            CurrentFolder::AltLimits => "Alt_Limits",
            CurrentFolder::AncillaryServicesPayments => "Ancillary_Services_Payments",
            CurrentFolder::AuctionUnitsReports => "Auction_Units_Reports",
            CurrentFolder::BidmoveComplete => "Bidmove_Complete",
            CurrentFolder::BidmoveSummary => "Bidmove_Summary",
            CurrentFolder::Billing => "Billing",
            CurrentFolder::CauserPays => "Causer_Pays",
            CurrentFolder::CauserPaysElements => "Causer_Pays_Elements",
            CurrentFolder::CauserPaysRslcpf => "Causer_Pays_Rslcpf",
            CurrentFolder::CauserPaysScada => "Causer_Pays_Scada",
            CurrentFolder::CDEII => "CDEII",
            CurrentFolder::CSCCSPConstraintList => "CSC_CSP_ConstraintList",
            CurrentFolder::CSCCSPSettlements => "CSC_CSP_Settlements",
            CurrentFolder::DailyReports => "Daily_Reports",
            CurrentFolder::DAILYOCD => "DAILYOCD",
            CurrentFolder::DirectionsReconciliation => "Directions_Reconciliation",
            CurrentFolder::DispatchIRSR => "Dispatch_IRSR",
            CurrentFolder::DISPATCHNEGATIVERESIDUE => "DISPATCH_NEGATIVE_RESIDUE",
            CurrentFolder::DispatchReports => "Dispatch_Reports",
            CurrentFolder::DispatchSCADA => "Dispatch_SCADA",
            CurrentFolder::DispatchISReports => "DispatchIS_Reports",
            CurrentFolder::DispatchpricesPREAP => "Dispatchprices_PRE_AP",
            CurrentFolder::DWGM => "DWGM",
            CurrentFolder::ECGS => "ECGS",
            CurrentFolder::GasSupplyGuarantee => "Gas_Supply_Guarantee",
            CurrentFolder::GBB => "GBB",
            CurrentFolder::GSH => "GSH",
            CurrentFolder::HighImpactOutages => "HighImpactOutages",
            CurrentFolder::HistDemand => "HistDemand",
            CurrentFolder::IBEI => "IBEI",
            CurrentFolder::MarginalLossFactors => "Marginal_Loss_Factors",
            CurrentFolder::MarketNotice => "Market_Notice",
            CurrentFolder::MCCDispatch => "MCCDispatch",
            CurrentFolder::MediumTermPASAReports => "Medium_Term_PASA_Reports",
            CurrentFolder::MktsuspPricing => "Mktsusp_Pricing",
            CurrentFolder::MMSDataModelReport => "MMSDataModelReport",
            CurrentFolder::MTPASADUIDAvailability => "MTPASA_DUIDAvailability",
            CurrentFolder::MTPASARegionAvailability => "MTPASA_RegionAvailability",
            CurrentFolder::Network => "Network",
            CurrentFolder::NextDayActualGen => "Next_Day_Actual_Gen",
            CurrentFolder::NEXTDAYAVAILSUBMISSCLUSTER => "NEXT_DAY_AVAIL_SUBMISS_CLUSTER",
            CurrentFolder::NEXTDAYAVAILSUBMISSDAY => "NEXT_DAY_AVAIL_SUBMISS_DAY",
            CurrentFolder::NextDayDispatch => "Next_Day_Dispatch",
            CurrentFolder::NextDayIntermittentDS => "Next_Day_Intermittent_DS",
            CurrentFolder::NEXTDAYMCCDISPATCH => "NEXT_DAY_MCCDISPATCH",
            CurrentFolder::NextDayOfferEnergy => "Next_Day_Offer_Energy",
            CurrentFolder::NextDayOfferFCAS => "Next_Day_Offer_FCAS",
            CurrentFolder::NextDayPreDispatch => "Next_Day_PreDispatch",
            CurrentFolder::NextDayPreDispatchD => "Next_Day_PreDispatchD",
            CurrentFolder::NextDayTrading => "Next_Day_Trading",
            CurrentFolder::OperationalDemand => "Operational_Demand",
            CurrentFolder::P5Reports => "P5_Reports",
            CurrentFolder::PasaSnap => "PasaSnap",
            CurrentFolder::PD7Day => "PD7Day",
            CurrentFolder::PDPASA => "PDPASA",
            CurrentFolder::PredispatchIRSR => "Predispatch_IRSR",
            CurrentFolder::PredispatchReports => "Predispatch_Reports",
            CurrentFolder::PredispatchSensitivities => "Predispatch_Sensitivities",
            CurrentFolder::PredispatchISReports => "PredispatchIS_Reports",
            CurrentFolder::PublicPrices => "Public_Prices",
            CurrentFolder::PublishedModelDataAccess => "PublishedModelDataAccess",
            CurrentFolder::RegionalSummaryReport => "Regional_Summary_Report",
            CurrentFolder::ReserveContractRecovery => "Reserve_Contract_Recovery",
            CurrentFolder::ROOFTOPPVActual => "ROOFTOP_PV/ACTUAL",
            CurrentFolder::ROOFTOPPVForecast => "ROOFTOP_PV/FORECAST",
            CurrentFolder::Settlements => "Settlements",
            CurrentFolder::SEVENDAYOUTLOOKFULL => "SEVENDAYOUTLOOK_FULL",
            CurrentFolder::SEVENDAYOUTLOOKPEAK => "SEVENDAYOUTLOOK_PEAK",
            CurrentFolder::ShortTermPASAReports => "Short_Term_PASA_Reports",
            CurrentFolder::SRABids => "SRA_Bids",
            CurrentFolder::SRANSRRECONCILIATION => "SRA_NSR_RECONCILIATION",
            CurrentFolder::SRAOffers => "SRA_Offers",
            CurrentFolder::SRAResults => "SRA_Results",
            CurrentFolder::STTM => "STTM",
            CurrentFolder::SupplyDemand => "SupplyDemand",
            CurrentFolder::TradingCumulativePrice => "Trading_Cumulative_Price",
            CurrentFolder::TradingIRSR => "Trading_IRSR",
            CurrentFolder::TradingISReports => "TradingIS_Reports",
            CurrentFolder::VicGas => "VicGas",
            CurrentFolder::VwaFcasPrices => "Vwa_Fcas_Prices",
            CurrentFolder::WDRCAPACITYNOSCADA => "WDR_CAPACITY_NO_SCADA",
            CurrentFolder::WeeklyBulletin => "Weekly_Bulletin",
            CurrentFolder::WeeklyConstraintReports => "Weekly_Constraint_Reports",
            CurrentFolder::YesterdaysBidsReports => "Yesterdays_Bids_Reports",
            CurrentFolder::YesterdaysMNSPBidsReports => "Yesterdays_MNSPBids_Reports",
        }
    }
}

#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum ArchiveFolder {
    AdjustedPricesReports, // M-1
    BidmoveComplete,       // M-2
    // BidmoveSummary, //
    Billing, // M-2
    // CDEII,
    DailyReports, // M-1
    // DAILYOCD,
    DispatchIRSR,            // D
    DispatchNegativeResidue, // D
    DispatchReports,         // D
    DispatchSCADA,           // D
    // DispatchISFCASFix,
    DispatchISReports,   // D
    DispatchpricesPREAP, // D
    // GSH, // Consider later
    HistDemand, // M-1
    // MarketNotice,
    MCCDispatch,              // D
    MediumTermPASAReports,    // M-1
    MTPASADUIDAvailability,   // M-1
    MTPASARegionAvailability, // M-1
    Network,                  // W-Fri
    NextDayActualGen,
    NEXTDAYAVAILSUBMISSCLUSTER,
    NEXTDAYAVAILSUBMISSDAY,
    NextDayDispatch,
    NextDayIntermittentDS,
    NEXTDAYMCCDISPATCH,
    NextDayOfferEnergy,
    NextDayOfferFCAS,
    NextDayPreDispatch,
    NextDayPreDispatchD,
    NextDayTrading,
    OperationalDemand,
    P5Reports,
    PDPASA,
    PredispatchIRSR,
    PredispatchReports,
    PredispatchSensitivities,
    PredispatchISReports,
    PublicPrices,
    ROOFTOPPVActual,
    ROOFTOPPVForecast,
    Settlements,
    SEVENDAYOUTLOOKFULL,
    SEVENDAYOUTLOOKPEAK,
    ShortTermPASAReports,
    TradingCumulativePrice,
    TradingIRSR,
    TradingISReports,
    WDRCAPACITYNOSCADA,
    WeeklyBulletin,
    YesterdaysBidsReports,
    YesterdaysMNSPBidsReports,
}

// resolution can be daily or monthly
impl ArchiveFolder {
    pub fn expected_by(&self, _effective_date: NaiveDate) -> DateTime<Utc> {
        todo!()
    }
    pub fn url(&self) -> String {
        format!("{NEMWEB}/{ARCHIVE}/{}", self.folder_name())
    }
    pub fn folder_name(&self) -> &'static str {
        match self {
            ArchiveFolder::AdjustedPricesReports => "Adjusted_Prices_Reports",
            ArchiveFolder::BidmoveComplete => "Bidmove_Complete",
            // ArchiveFolder::BidmoveSummary => "Bidmove_Summary",
            ArchiveFolder::Billing => "Billing",
            // ArchiveFolder::CDEII => "CDEII",
            ArchiveFolder::DailyReports => "Daily_Reports",
            // ArchiveFolder::DAILYOCD => "DAILYOCD",
            ArchiveFolder::DispatchIRSR => "Dispatch_IRSR",
            ArchiveFolder::DispatchNegativeResidue => "Dispatch_Negative_Residue",
            ArchiveFolder::DispatchReports => "Dispatch_Reports",
            ArchiveFolder::DispatchSCADA => "Dispatch_SCADA",
            // ArchiveFolder::DispatchISFCASFix => "DispatchIS_FCAS_Fix",
            ArchiveFolder::DispatchISReports => "DispatchIS_Reports",
            ArchiveFolder::DispatchpricesPREAP => "Dispatchprices_PRE_AP",
            // ArchiveFolder::GSH => "GSH",
            ArchiveFolder::HistDemand => "HistDemand",
            // ArchiveFolder::MarketNotice => "Market_Notice",
            ArchiveFolder::MCCDispatch => "MCCDispatch",
            ArchiveFolder::MediumTermPASAReports => "Medium_Term_PASA_Reports",
            ArchiveFolder::MTPASADUIDAvailability => "MTPASA_DUIDAvailability",
            ArchiveFolder::MTPASARegionAvailability => "MTPASA_RegionAvailability",
            ArchiveFolder::Network => "Network",
            ArchiveFolder::NextDayActualGen => "Next_Day_Actual_Gen",
            ArchiveFolder::NEXTDAYAVAILSUBMISSCLUSTER => "NEXT_DAY_AVAIL_SUBMISS_CLUSTER",
            ArchiveFolder::NEXTDAYAVAILSUBMISSDAY => "NEXT_DAY_AVAIL_SUBMISS_DAY",
            ArchiveFolder::NextDayDispatch => "Next_Day_Dispatch",
            ArchiveFolder::NextDayIntermittentDS => "Next_Day_Intermittent_DS",
            ArchiveFolder::NEXTDAYMCCDISPATCH => "NEXT_DAY_MCCDISPATCH",
            ArchiveFolder::NextDayOfferEnergy => "Next_Day_Offer_Energy",
            ArchiveFolder::NextDayOfferFCAS => "Next_Day_Offer_FCAS",
            ArchiveFolder::NextDayPreDispatch => "Next_Day_PreDispatch",
            ArchiveFolder::NextDayPreDispatchD => "Next_Day_PreDispatchD",
            ArchiveFolder::NextDayTrading => "Next_Day_Trading",
            ArchiveFolder::OperationalDemand => "Operational_Demand",
            ArchiveFolder::P5Reports => "P5_Reports",
            ArchiveFolder::PDPASA => "PDPASA",
            ArchiveFolder::PredispatchIRSR => "Predispatch_IRSR",
            ArchiveFolder::PredispatchReports => "Predispatch_Reports",
            ArchiveFolder::PredispatchSensitivities => "Predispatch_Sensitivities",
            ArchiveFolder::PredispatchISReports => "PredispatchIS_Reports",
            ArchiveFolder::PublicPrices => "Public_Prices",
            ArchiveFolder::ROOFTOPPVActual => "ROOFTOP_PV/ACTUAL",
            ArchiveFolder::ROOFTOPPVForecast => "ROOFTOP_PV/FORECAST",
            ArchiveFolder::Settlements => "Settlements",
            ArchiveFolder::SEVENDAYOUTLOOKFULL => "SEVENDAYOUTLOOK_FULL",
            ArchiveFolder::SEVENDAYOUTLOOKPEAK => "SEVENDAYOUTLOOK_PEAK",
            ArchiveFolder::ShortTermPASAReports => "Short_Term_PASA_Reports",
            ArchiveFolder::TradingCumulativePrice => "Trading_Cumulative_Price",
            ArchiveFolder::TradingIRSR => "Trading_IRSR",
            ArchiveFolder::TradingISReports => "TradingIS_Reports",
            ArchiveFolder::WDRCAPACITYNOSCADA => "WDR_CAPACITY_NO_SCADA",
            ArchiveFolder::WeeklyBulletin => "Weekly_Bulletin",
            ArchiveFolder::YesterdaysBidsReports => "Yesterdays_Bids_Reports",
            ArchiveFolder::YesterdaysMNSPBidsReports => "Yesterdays_MNSPBids_Reports",
        }
    }
}
