[package]
name = "date-impl"
version = "0.1.0"
edition = "2021"


[lib]
path = "date-impl.rs"

[dependencies.chrono]
workspace = true
default-features = false 
optional = true

[dev-dependencies]
chrono = "0.4"
criterion = "0.5.0"

[[bench]]
name = "calc-ymd"
harness = false
path = "calc-ymd.rs"