[package]
name = "resolution"
version = "0.1.0"
edition = "2024"


[dependencies.serde]
workspace = true
optional = true

[dependencies.chrono]
workspace = true
default-features = false
optional = true 

[dependencies.date]
path = "../date"

[dev-dependencies]
serde_json = "1.0.115"
chrono-tz = "0.10.0"
chrono = "0.4"
jiff = "0.2.13"
criterion = "0.5.0"

[features]
serde = ["dep:serde","chrono/serde", "date/serde"]
std = ["chrono/std","date/std"]
chrono = ["dep:chrono", "date/chrono"]
default = ["std","serde","chrono"]

